simple_django/forms/core/urls.py
# from core.views import IndexView, CreateStudentView, CreateGroupView,
from django.urls import path
from core.views import IndexView, StudentCreateView, GroupCreateView, GroupUpdateView, StudentUpdateView, TeachersView, StudentsView, delete_student, delete_group

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('teachers/', TeachersView.as_view(), name='teachers'),
    path('students/', StudentsView.as_view(), name='students'),
    path('create-student/', StudentCreateView.as_view(), name='create-student'),
    path('create-group/', GroupCreateView.as_view(), name='create-group'),
    path('update-group/<int:group_id>/', GroupUpdateView.as_view(), name='update-group'),
    path('update-student/<int:student_id>/', StudentUpdateView.as_view(), name='update-student'),
    path('delete-student/<int:student_id>/', delete_student, name='delete-student'),
    path('delete-group/<int:group_id>/', delete_group, name='delete-group'),
]

simple_django/forms/forms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(("core.urls", "core"), namespace='main'))
]

simple_django/forms/core/models.py
from django.db import models


class Group(models.Model):

    name = models.CharField(max_length=255, verbose_name="Название группы")
    students = models.ManyToManyField("core.Student", blank=True)
    teacher_name = models.CharField(max_length=255, verbose_name="Имя учителя", null=True)

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя")
    age = models.IntegerField(null=True)

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"

    def __str__(self):
        return self.name

simple_django/forms/core/forms.py
from django import forms
from core.models import Group, Student


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'students': forms.widgets.CheckboxSelectMultiple()
        }


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = '__all__'

simple_django/forms/core/views.py
from django.views.generic import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.views.generic import FormView
from django.shortcuts import redirect
from django.db.models import Avg, Max, Min, Count
from core.forms import GroupForm, StudentForm
from django.urls.base import reverse_lazy
from core.models import Student, Group


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        groups = Group.objects.all().values('id', 'name', 'teacher_name').annotate(
            student_count=Count('students'),
            student_avg=Avg('students__age'),
            student_max=Max('students__age'),
            student_min=Min('students__age'),
        )

        return {
                'groups': groups,
            }


class TeachersView(TemplateView):
    template_name = "teachers.html"

    def get_context_data(self, **kwargs):
        groups = Group.objects.all().values('id', 'name', 'teacher_name')

        return {
            'groups': groups
        }


class StudentsView(TemplateView):
    template_name = "students.html"

    def get_context_data(self, **kwargs):
        students = Student.objects.all()
        print(students)
        return {
            'students': students
        }


class StudentCreateView(CreateView):
    template_name = 'create.html'
    success_url = reverse_lazy('main:teachers')
    model = Student
    fields = '__all__'


class GroupCreateView(FormView):
    template_name = 'create.html'
    form_class = GroupForm
    success_url = reverse_lazy('main:teachers')

    def form_valid(self, form):
        form.save()
        return super(GroupCreateView, self).form_valid(form)


class StudentUpdateView(UpdateView):
    template_name = 'update_student.html'

    success_url = reverse_lazy('main:students')
    model = Student
    form_class = StudentForm
    pk_url_kwarg = 'student_id'


class GroupUpdateView(UpdateView):
    template_name = 'update_group.html'

    success_url = reverse_lazy('main:teachers')
    model = Group
    form_class = GroupForm
    pk_url_kwarg = 'group_id'


def delete_student(request, student_id=None):
    post_to_delete = Student.objects.get(id=student_id)
    post_to_delete.delete()

    return redirect('main:home')


def delete_group(request, group_id=None):
    post_to_delete = Group.objects.get(id=group_id)
    post_to_delete.delete()

    return redirect('main:teachers')

simple_django/forms/core/templates/create.html
{% load bootstrap %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>
        <div class="container">
            <form role="form" method="post">{% csrf_token %}
                {{ form|bootstrap }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </body>
</html>

simple_django/forms/core/templates/index.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <br>
        <div class="container">
            <div class="col-md-12">
                <form method="get">
                    <div class="row">
                        <div class="col-md-5">
                            <a class="btn btn-primary" href="{% url 'main:students' %}">STUDENTS</a>
                        </div>
                        <div class="col-md-5">
                            <a class="btn btn-primary" href="{% url 'main:teachers' %}">Teachers</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Group</th>
                            <th>Number_of_students</th>
                            <th>AVG_age_of_students</th>
                            <th>MAX_age_of_students</th>
                            <th>MIN_age_of_students</th>
                            <th>Teacher</th>
                            <th></th>
                        </tr>
                        {% for group in groups %}
                            <tr>
                                <td>{{group.name}}</td>
                                <td>{{group.student_count}}</td>
                                <td>{{group.student_avg}}</td>
                                <td>{{group.student_max}}</td>
                                <td>{{group.student_min}}</td>
                                <td>{{group.teacher_name}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

simple_django/forms/core/templates/students.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <br>
        <div class="container">
            <div class="col-md-8">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:home' %}">Main</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Student</th>
                        </tr>
                        {% for student in students %}
                            <tr>
                                <td>{{student.name}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:update-student' student.id %}">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

simple_django/forms/core/templates/teachers.html
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <br>
        <div class="container">
            <div class="col-md-11">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:home' %}">MAIN</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:create-group' %}">Add_Group</a>
                        </div>
                        <div class="col-md-3">
                            <a class="btn btn-primary" href="{% url 'main:create-student' %}">Create_Student</a>
                        </div>
                        <div class="col-md-3">
                            <a class="btn btn-primary" href="{% url 'main:students' %}">Edit_STUDENTS</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Group</th>
                            <th>Teacher</th>
                        </tr>
                        {% for group in groups %}
                            <tr>
                                <td>{{group.name}}</td>
                                <td>{{group.teacher_name}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:update-group' group.id %}">Edit</a>
                                    {#<a class="btn btn-primary" href="{% url 'group:update' group.id %}">Edit</a>#}
                                    <a class="btn btn-primary" href="{% url 'main:delete-group' group.id %}">Remove</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

simple_django/forms/core/templates/update_group.html
{% load bootstrap %}

<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>
        <div class="container">
            <form role="form" method="post">{% csrf_token %}
                {{ form|bootstrap }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </body>
</html>

simple_django/forms/core/templates/update_student.html
{% load bootstrap %}

<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>
        <div class="container">
            <form role="form" method="post">{% csrf_token %}
                {{ form|bootstrap }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <a class="btn btn-primary" href="{% url 'main:delete-student' student.id %}">Delete</a>
                </div>
            </form>
        </div>
    </body>
</html>